[2022-03-15 10:17:02,349] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:16:46.638985+00:00 [queued]>
[2022-03-15 10:17:02,395] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:16:46.638985+00:00 [queued]>
[2022-03-15 10:17:02,398] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:17:02,399] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-15 10:17:02,401] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:17:02,453] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_weather_table> on 2022-03-15 10:16:46.638985+00:00
[2022-03-15 10:17:02,463] {standard_task_runner.py:52} INFO - Started process 20496 to run task
[2022-03-15 10:17:02,472] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_weather_table', 'manual__2022-03-15T10:16:46.638985+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp1xplw5f3', '--error-file', '/tmp/tmpwfmlpzkh']
[2022-03-15 10:17:02,476] {standard_task_runner.py:77} INFO - Job 19: Subtask create_weather_table
[2022-03-15 10:17:02,720] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:16:46.638985+00:00 [running]> on host 0bb54ecb374d
[2022-03-15 10:17:02,918] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:16:46.638985+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:16:46.638985+00:00
[2022-03-15 10:17:02,944] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-03-15 10:17:02,954] {dbapi.py:225} INFO - Running statement: -- creating weather table
CREATE TABLE IF NOT EXISTS weather_table(
state_name VARCHAR NOT NULL PRIMARY KEY UNIQUE,
description VARCHAR NOT NULL,
temperature VARCHAR NOT NULL,
feels_like VARCHAR NOT NULL,
temp_min VARCHAR NOT NULL,
temp_max VARCHAR NOT NULL,
humidity VARCHAR NOT NULL,
clouds VARCHAR NOT NULL);, parameters: None
[2022-03-15 10:17:02,958] {postgres.py:73} INFO - NOTICE:  relation "weather_table" already exists, skipping

[2022-03-15 10:17:02,995] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_weather_table, execution_date=20220315T101646, start_date=20220315T101702, end_date=20220315T101702
[2022-03-15 10:17:03,091] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:17:03,189] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
