[2022-03-14 15:46:39,912] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-14T15:46:36.998676+00:00 [queued]>
[2022-03-14 15:46:39,950] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-14T15:46:36.998676+00:00 [queued]>
[2022-03-14 15:46:39,952] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 15:46:39,954] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-14 15:46:39,956] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 15:46:40,003] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2022-03-14 15:46:36.998676+00:00
[2022-03-14 15:46:40,013] {standard_task_runner.py:52} INFO - Started process 3740 to run task
[2022-03-14 15:46:40,021] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'fetch_weather_data', 'manual__2022-03-14T15:46:36.998676+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp0ufmkimg', '--error-file', '/tmp/tmp6oakyg0n']
[2022-03-14 15:46:40,024] {standard_task_runner.py:77} INFO - Job 9: Subtask fetch_weather_data
[2022-03-14 15:46:40,158] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.fetch_weather_data manual__2022-03-14T15:46:36.998676+00:00 [running]> on host 0bb54ecb374d
[2022-03-14 15:46:40,307] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T15:46:36.998676+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T15:46:36.998676+00:00
[2022-03-14 15:46:46,410] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 15:46:46,445] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=fetch_weather_data, execution_date=20220314T154636, start_date=20220314T154639, end_date=20220314T154646
[2022-03-14 15:46:46,503] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 15:46:46,613] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
