[2022-03-15 10:18:20,266] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:18:09.024018+00:00 [queued]>
[2022-03-15 10:18:20,303] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:18:09.024018+00:00 [queued]>
[2022-03-15 10:18:20,305] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:18:20,306] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-15 10:18:20,307] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:18:20,350] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_weather_table> on 2022-03-15 10:18:09.024018+00:00
[2022-03-15 10:18:20,359] {standard_task_runner.py:52} INFO - Started process 20614 to run task
[2022-03-15 10:18:20,366] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_weather_table', 'manual__2022-03-15T10:18:09.024018+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp25wwbe21', '--error-file', '/tmp/tmp25udv2bu']
[2022-03-15 10:18:20,369] {standard_task_runner.py:77} INFO - Job 22: Subtask create_weather_table
[2022-03-15 10:18:20,524] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:18:09.024018+00:00 [running]> on host 0bb54ecb374d
[2022-03-15 10:18:20,682] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:18:09.024018+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:18:09.024018+00:00
[2022-03-15 10:18:20,704] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-03-15 10:18:20,714] {dbapi.py:225} INFO - Running statement: -- creating weather table
CREATE TABLE IF NOT EXISTS weather_table(
state_name VARCHAR NOT NULL PRIMARY KEY UNIQUE,
description VARCHAR NOT NULL,
temperature VARCHAR NOT NULL,
feels_like VARCHAR NOT NULL,
temp_min VARCHAR NOT NULL,
temp_max VARCHAR NOT NULL,
humidity VARCHAR NOT NULL,
clouds VARCHAR NOT NULL);, parameters: None
[2022-03-15 10:18:20,717] {postgres.py:73} INFO - NOTICE:  relation "weather_table" already exists, skipping

[2022-03-15 10:18:20,749] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_weather_table, execution_date=20220315T101809, start_date=20220315T101820, end_date=20220315T101820
[2022-03-15 10:18:20,832] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:18:20,918] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
