[2022-03-15 10:16:50,783] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:16:46.638985+00:00 [queued]>
[2022-03-15 10:16:50,831] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:16:46.638985+00:00 [queued]>
[2022-03-15 10:16:50,834] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:16:50,836] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-15 10:16:50,837] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:16:50,898] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2022-03-15 10:16:46.638985+00:00
[2022-03-15 10:16:50,907] {standard_task_runner.py:52} INFO - Started process 20473 to run task
[2022-03-15 10:16:50,915] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'fetch_weather_data', 'manual__2022-03-15T10:16:46.638985+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp_t_bl0_2', '--error-file', '/tmp/tmp07cmwh06']
[2022-03-15 10:16:50,919] {standard_task_runner.py:77} INFO - Job 18: Subtask fetch_weather_data
[2022-03-15 10:16:51,096] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:16:46.638985+00:00 [running]> on host 0bb54ecb374d
[2022-03-15 10:16:51,284] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:16:46.638985+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:16:46.638985+00:00
[2022-03-15 10:16:59,615] {python.py:175} INFO - Done. Returned value was: None
[2022-03-15 10:16:59,653] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=fetch_weather_data, execution_date=20220315T101646, start_date=20220315T101650, end_date=20220315T101659
[2022-03-15 10:16:59,719] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:16:59,843] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
