[2022-03-15 10:51:45,596] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:51:41.839785+00:00 [queued]>
[2022-03-15 10:51:45,636] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:51:41.839785+00:00 [queued]>
[2022-03-15 10:51:45,638] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:51:45,639] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-15 10:51:45,640] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:51:45,687] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2022-03-15 10:51:41.839785+00:00
[2022-03-15 10:51:45,696] {standard_task_runner.py:52} INFO - Started process 22874 to run task
[2022-03-15 10:51:45,703] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'fetch_weather_data', 'manual__2022-03-15T10:51:41.839785+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpd6tc7rhj', '--error-file', '/tmp/tmp8u_3cvh0']
[2022-03-15 10:51:45,706] {standard_task_runner.py:77} INFO - Job 24: Subtask fetch_weather_data
[2022-03-15 10:51:45,858] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:51:41.839785+00:00 [running]> on host 0bb54ecb374d
[2022-03-15 10:51:46,024] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:51:41.839785+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:51:41.839785+00:00
[2022-03-15 10:51:52,452] {python.py:175} INFO - Done. Returned value was: None
[2022-03-15 10:51:52,539] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=fetch_weather_data, execution_date=20220315T105141, start_date=20220315T105145, end_date=20220315T105152
[2022-03-15 10:51:52,628] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:51:52,738] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
