[2022-03-15 10:18:11,908] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:18:09.024018+00:00 [queued]>
[2022-03-15 10:18:11,951] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:18:09.024018+00:00 [queued]>
[2022-03-15 10:18:11,953] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:18:11,954] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-15 10:18:11,956] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:18:12,008] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2022-03-15 10:18:09.024018+00:00
[2022-03-15 10:18:12,018] {standard_task_runner.py:52} INFO - Started process 20604 to run task
[2022-03-15 10:18:12,029] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'fetch_weather_data', 'manual__2022-03-15T10:18:09.024018+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpju_g60cu', '--error-file', '/tmp/tmp672p0md7']
[2022-03-15 10:18:12,033] {standard_task_runner.py:77} INFO - Job 21: Subtask fetch_weather_data
[2022-03-15 10:18:12,200] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.fetch_weather_data manual__2022-03-15T10:18:09.024018+00:00 [running]> on host 0bb54ecb374d
[2022-03-15 10:18:12,384] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:18:09.024018+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:18:09.024018+00:00
[2022-03-15 10:18:18,273] {python.py:175} INFO - Done. Returned value was: None
[2022-03-15 10:18:18,306] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=fetch_weather_data, execution_date=20220315T101809, start_date=20220315T101811, end_date=20220315T101818
[2022-03-15 10:18:18,377] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:18:18,515] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
