[2022-03-14 13:43:27,137] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-14T13:43:23.298505+00:00 [queued]>
[2022-03-14 13:43:27,185] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.fetch_weather_data manual__2022-03-14T13:43:23.298505+00:00 [queued]>
[2022-03-14 13:43:27,187] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 13:43:27,189] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-14 13:43:27,190] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 13:43:27,240] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2022-03-14 13:43:23.298505+00:00
[2022-03-14 13:43:27,249] {standard_task_runner.py:52} INFO - Started process 2026 to run task
[2022-03-14 13:43:27,256] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'fetch_weather_data', 'manual__2022-03-14T13:43:23.298505+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp9xr650qc', '--error-file', '/tmp/tmp0xbn4261']
[2022-03-14 13:43:27,260] {standard_task_runner.py:77} INFO - Job 14: Subtask fetch_weather_data
[2022-03-14 13:43:27,416] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.fetch_weather_data manual__2022-03-14T13:43:23.298505+00:00 [running]> on host e0810cf0708b
[2022-03-14 13:43:27,659] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=fetch_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T13:43:23.298505+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T13:43:23.298505+00:00
[2022-03-14 13:43:33,886] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 13:43:33,923] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=fetch_weather_data, execution_date=20220314T134323, start_date=20220314T134327, end_date=20220314T134333
[2022-03-14 13:43:34,005] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 13:43:34,121] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
