[2022-03-14 13:43:41,608] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.populate_weather_table manual__2022-03-14T13:43:23.298505+00:00 [queued]>
[2022-03-14 13:43:41,654] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.populate_weather_table manual__2022-03-14T13:43:23.298505+00:00 [queued]>
[2022-03-14 13:43:41,656] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 13:43:41,658] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-14 13:43:41,660] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 13:43:41,711] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): populate_weather_table> on 2022-03-14 13:43:23.298505+00:00
[2022-03-14 13:43:41,720] {standard_task_runner.py:52} INFO - Started process 2050 to run task
[2022-03-14 13:43:41,730] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'populate_weather_table', 'manual__2022-03-14T13:43:23.298505+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmps_00o1ly', '--error-file', '/tmp/tmpw_iq6caj']
[2022-03-14 13:43:41,734] {standard_task_runner.py:77} INFO - Job 16: Subtask populate_weather_table
[2022-03-14 13:43:41,906] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.populate_weather_table manual__2022-03-14T13:43:23.298505+00:00 [running]> on host e0810cf0708b
[2022-03-14 13:43:42,146] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=populate_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T13:43:23.298505+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T13:43:23.298505+00:00
[2022-03-14 13:43:42,178] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-03-14 13:43:42,192] {dbapi.py:225} INFO - Running statement: DROP TABLE IF EXISTS weather_table;
CREATE TABLE weather_table (
state_name VARCHAR NOT NULL,
description VARCHAR NOT NULL,
temperature VARCHAR NOT NULL,
feels_like VARCHAR NOT NULL,
temp_min VARCHAR NOT NULL,
temp_max VARCHAR NOT NULL,
humidity VARCHAR NOT NULL,
clouds VARCHAR NOT NULL);, parameters: None
[2022-03-14 13:43:42,263] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=populate_weather_table, execution_date=20220314T134323, start_date=20220314T134341, end_date=20220314T134342
[2022-03-14 13:43:42,388] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 13:43:42,484] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
