[2022-03-15 10:51:54,799] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:51:41.839785+00:00 [queued]>
[2022-03-15 10:51:54,838] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:51:41.839785+00:00 [queued]>
[2022-03-15 10:51:54,839] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:51:54,841] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-15 10:51:54,842] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:51:54,880] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_weather_table> on 2022-03-15 10:51:41.839785+00:00
[2022-03-15 10:51:54,888] {standard_task_runner.py:52} INFO - Started process 22897 to run task
[2022-03-15 10:51:54,895] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_weather_table', 'manual__2022-03-15T10:51:41.839785+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpoezyjh1y', '--error-file', '/tmp/tmpa_yi7kue']
[2022-03-15 10:51:54,898] {standard_task_runner.py:77} INFO - Job 25: Subtask create_weather_table
[2022-03-15 10:51:55,038] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_weather_table manual__2022-03-15T10:51:41.839785+00:00 [running]> on host 0bb54ecb374d
[2022-03-15 10:51:55,214] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:51:41.839785+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-15T10:51:41.839785+00:00
[2022-03-15 10:51:55,240] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-03-15 10:51:55,249] {dbapi.py:225} INFO - Running statement: -- creating weather table
CREATE TABLE IF NOT EXISTS weather_table(
state_name VARCHAR NOT NULL PRIMARY KEY UNIQUE,
description VARCHAR NOT NULL,
temperature VARCHAR NOT NULL,
feels_like VARCHAR NOT NULL,
temp_min VARCHAR NOT NULL,
temp_max VARCHAR NOT NULL,
humidity VARCHAR NOT NULL,
clouds VARCHAR NOT NULL);, parameters: None
[2022-03-15 10:51:55,253] {postgres.py:73} INFO - NOTICE:  relation "weather_table" already exists, skipping

[2022-03-15 10:51:55,288] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_weather_table, execution_date=20220315T105141, start_date=20220315T105154, end_date=20220315T105155
[2022-03-15 10:51:55,359] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 10:51:55,450] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
