[2022-03-14 15:46:49,050] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-14T15:46:36.998676+00:00 [queued]>
[2022-03-14 15:46:49,089] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.create_weather_table manual__2022-03-14T15:46:36.998676+00:00 [queued]>
[2022-03-14 15:46:49,091] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 15:46:49,092] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-14 15:46:49,094] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 15:46:49,132] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_weather_table> on 2022-03-14 15:46:36.998676+00:00
[2022-03-14 15:46:49,140] {standard_task_runner.py:52} INFO - Started process 3763 to run task
[2022-03-14 15:46:49,146] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_weather_table', 'manual__2022-03-14T15:46:36.998676+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp5awx6vlc', '--error-file', '/tmp/tmpyxfzsrmc']
[2022-03-14 15:46:49,150] {standard_task_runner.py:77} INFO - Job 10: Subtask create_weather_table
[2022-03-14 15:46:49,262] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_weather_table manual__2022-03-14T15:46:36.998676+00:00 [running]> on host 0bb54ecb374d
[2022-03-14 15:46:49,425] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T15:46:36.998676+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T15:46:36.998676+00:00
[2022-03-14 15:46:49,462] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-03-14 15:46:49,480] {dbapi.py:225} INFO - Running statement: DROP TABLE IF EXISTS weather_table;
CREATE TABLE weather_table (
state_name VARCHAR NOT NULL,
description VARCHAR NOT NULL,
temperature VARCHAR NOT NULL,
feels_like VARCHAR NOT NULL,
temp_min VARCHAR NOT NULL,
temp_max VARCHAR NOT NULL,
humidity VARCHAR NOT NULL,
clouds VARCHAR NOT NULL);, parameters: None
[2022-03-14 15:46:49,498] {postgres.py:73} INFO - NOTICE:  table "weather_table" does not exist, skipping

[2022-03-14 15:46:49,573] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_weather_table, execution_date=20220314T154636, start_date=20220314T154649, end_date=20220314T154649
[2022-03-14 15:46:49,647] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 15:46:49,747] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
