[2022-03-14 15:46:51,688] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.populate_weather_table manual__2022-03-14T15:46:36.998676+00:00 [queued]>
[2022-03-14 15:46:51,728] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: main_dag.populate_weather_table manual__2022-03-14T15:46:36.998676+00:00 [queued]>
[2022-03-14 15:46:51,730] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 15:46:51,731] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-03-14 15:46:51,732] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 15:46:51,772] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): populate_weather_table> on 2022-03-14 15:46:36.998676+00:00
[2022-03-14 15:46:51,780] {standard_task_runner.py:52} INFO - Started process 3776 to run task
[2022-03-14 15:46:51,787] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'populate_weather_table', 'manual__2022-03-14T15:46:36.998676+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmplyc3aeda', '--error-file', '/tmp/tmpc417xf7h']
[2022-03-14 15:46:51,790] {standard_task_runner.py:77} INFO - Job 11: Subtask populate_weather_table
[2022-03-14 15:46:51,905] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.populate_weather_table manual__2022-03-14T15:46:36.998676+00:00 [running]> on host 0bb54ecb374d
[2022-03-14 15:46:52,037] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=populate_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T15:46:36.998676+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T15:46:36.998676+00:00
[2022-03-14 15:46:52,068] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2022-03-14 15:46:52,079] {dbapi.py:225} INFO - Running statement: DROP TABLE IF EXISTS weather_table;
CREATE TABLE weather_table (
state_name VARCHAR NOT NULL,
description VARCHAR NOT NULL,
temperature VARCHAR NOT NULL,
feels_like VARCHAR NOT NULL,
temp_min VARCHAR NOT NULL,
temp_max VARCHAR NOT NULL,
humidity VARCHAR NOT NULL,
clouds VARCHAR NOT NULL);, parameters: None
[2022-03-14 15:46:52,128] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=populate_weather_table, execution_date=20220314T154636, start_date=20220314T154651, end_date=20220314T154652
[2022-03-14 15:46:52,207] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 15:46:52,306] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
